// config.bin - 04:48:59 01/18/13, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define private		0
#define protected		1
#define public		2

class CfgPatches {
	class sah_civilian_patch {
		units[] = {"sah_civilian1_pants", "sah_civilian2_pants", "sah_civilian3_pants", "sah_civilian4_pants""sah_civilian5_pants", "sah_civilian6_pants", "sah_civilian7_pants", "sah_civilian1_shorts", "sah_civilian2_shorts", "sah_civilian3_shorts", "sah_civilian4_shorts""sah_civilian5_shorts", "sah_civilian6_shorts", "sah_civilian7_shorts"};
		weapons[] = {};
		requiredVersion = 1.0;
		requiredAddons[] = {};
	};
};

class CfgVehicleClasses {
	class sah_civilian_class {
		displayName = "Civilians";
	};
	
	class sah_civilian_class_shorts {
		displayName = "Civilians (shorts)";
	};
};

class CfgFactionClasses {
	class sah_civilian_faction {
		displayName = "Sahrani People";
		priority = 90;
		side = TWest;
	};
};

class CfgVehicles {
	class All;	// External class reference
	class AllVehicles;	// External class reference
	class ThingEffect;	// External class reference
	class Land;	// External class reference
	class Man;	// External class reference
	class CAManBase;	// External class reference
	class USMC_Soldier2;	// External class reference
	
	class sah_civilian1_pants : USMC_Soldier2 {
		scope = public;
		displayName = "Civilian 1";
		model = "\sara_civilians\civil_1_tshirt.p3d";
		side = 1;
		weapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "sah_civilian_class";
		faction = "sah_civilian_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		identityTypes[] = {"Head_USMC"};
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		
		class Wounds {
			tex[] = {};
			mat[] = {"sara_civilians\data\civil_tshirt_body.rvmat", "sara_civilians\data\civil_tshirt_body_wound1.rvmat", "sara_civilians\data\civil_tshirt_body_wound2.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_white.rvmat", "sara_civilians\data\civil_1_tshirt_hhl_wound1.rvmat", "sara_civilians\data\civil_1_tshirt_hhl_wound2.rvmat"};
		};
	};
	
	class sah_civilian2_pants : sah_civilian1_pants {
		scope = public;
		displayName = "Civilian 2";
		model = "\sara_civilians\civil_2_tshirt.p3d";
	};
	
	class sah_civilian3_pants : sah_civilian1_pants {
		scope = public;
		displayName = "Civilian 3";
		model = "\sara_civilians\civil_3_tshirt.p3d";
	};
	
	class sah_civilian4_pants : sah_civilian1_pants {
		scope = public;
		displayName = "Civilian 4";
		model = "\sara_civilians\civil_4_tshirt.p3d";
	};
	
	class sah_civilian5_pants : sah_civilian1_pants {
		scope = public;
		displayName = "Civilian 5";
		model = "\sara_civilians\civil_5_tshirt.p3d";
	};
	
	class sah_civilian6_pants : sah_civilian1_pants {
		scope = public;
		displayName = "Civilian 6";
		model = "\sara_civilians\civil_6_tshirt.p3d";
	};
	
	class sah_civilian7_pants : sah_civilian1_pants {
		scope = public;
		displayName = "Civilian 7";
		model = "\sara_civilians\civil_7_tshirt.p3d";
	};
	
	class sah_civilian1_shorts : USMC_Soldier2 {
		scope = public;
		displayName = "Civilian 1";
		model = "\sara_civilians\civil_1_tshirt_shorts.p3d";
		side = 1;
		weapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "sah_civilian_class_shorts";
		faction = "sah_civilian_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		identityTypes[] = {"Head_USMC"};
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		
		class Wounds {
			tex[] = {};
			mat[] = {"sara_civilians\data\civil_tshirt_shorts_body.rvmat", "sara_civilians\data\civil_tshirt_shorts_body_wound1.rvmat", "sara_civilians\data\civil_tshirt_shorts_body_wound2.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_white.rvmat", "sara_civilians\data\civil_1_tshirt_hhl_wound1.rvmat", "sara_civilians\data\civil_1_tshirt_hhl_wound2.rvmat"};
		};
	};
	
	class sah_civilian2_shorts : sah_civilian1_shorts {
		scope = public;
		displayName = "Civilian 2";
		model = "\sara_civilians\civil_2_tshirt_shorts.p3d";
	};
	
	class sah_civilian3_shorts : sah_civilian1_shorts {
		scope = public;
		displayName = "Civilian 3";
		model = "\sara_civilians\civil_3_tshirt_shorts.p3d";
	};
	
	class sah_civilian4_shorts : sah_civilian1_shorts {
		scope = public;
		displayName = "Civilian 4";
		model = "\sara_civilians\civil_4_tshirt_shorts.p3d";
	};
	
	class sah_civilian5_shorts : sah_civilian1_shorts {
		scope = public;
		displayName = "Civilian 5";
		model = "\sara_civilians\civil_5_tshirt_shorts.p3d";
	};
	
	class sah_civilian6_shorts : sah_civilian1_shorts {
		scope = public;
		displayName = "Civilian 6";
		model = "\sara_civilians\civil_6_tshirt_shorts.p3d";
	};
	
	class sah_civilian7_shorts : sah_civilian1_shorts {
		scope = public;
		displayName = "Civilian 7";
		model = "\sara_civilians\civil_7_tshirt_shorts.p3d";
	};
};
