// config.bin - 14:41:20 01/29/13, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

class CfgPatches {
	class d3z_shotguns {
		units[] = {};
		weapons[] = {"d3z_lanber", "d3z_maxus"};
		requiredVersion = 1.53;
		requiredAddons[] = {};
		version = 1.0;
	};
};

class cfgrecoils {
	recoil_shotgun[] = {0.04, 0.006*(  (9/7)), 0.05*.5*(  (9/7)), 0.04, 0.006*(  (9/7)), 0.05*.5*(  (9/7))};
};

class CfgWeaponCursors {
	class Cannon;	// External class reference
	
	class ShotgunCursor : Cannon {
		texture = "\ca\ui\Data\cursor_circle_ca.paa";
		color[] = {0.6, 0.8392, 0.4706, 1};
		shadowEnabled = 1;
	};
};

class cfgammo {
	class bulletcore;	// External class reference
	class bulletbase;	// External class reference
	
	class d3z_shot_light : bulletbase {
		hit = 10;
		indirectHit = 0;
		indirectHitRange = 0;
		cartridge = "";
		timetolive = 0.3;
		cost = 5;
		deflecting = 0;
		typicalSpeed = 450;
		visibleFire = 18;	// how much is visible when this weapon is fired
		audibleFire = 18;
		airFriction = -0.005;
		caliber = 0.4;
	};
	
	class d3z_shot_dim : bulletbase {
		hit = 10;
		indirectHit = 0;
		indirectHitRange = 0;
		cartridge = "";
		timetolive = 0.3;
		cost = 5;
		deflecting = 0;
		typicalSpeed = 450;
		visibleFire = 18;	// how much is visible when this weapon is fired
		audibleFire = 18;
		airFriction = -0.005;
		caliber = 0.4;
	};
	
	class d3z_ammo_shot : d3z_shot_light {};
	
	class d3z_ammo_shot_dim : d3z_shot_dim {};
	
	class d3z_ammo_shot_2 : d3z_shot_light {
		cartridge = "FxCartridge_slug";
	};
	
	class d3z_ammo_shot_2_dim : d3z_shot_dim {
		cartridge = "FxCartridge_slug";
	};
	
	class d3z_ammo_pel : bulletbase {
		hit = 2.1;
		model = "\ca\Weapons\Data\bullettracer\tracer_red";
		tracerColor[] = {0.7, 0.7, 0.5, 0.04};
		tracerColorR[] = {0.7, 0.7, 0.5, 0.04};
		tracerStartTime = 0;
		tracerEndTime = 2.4;
		tracerScale = 0.5;
		nvgOnly = "false";
		indirectHit = 1;
		indirectHitRange = 0.1;
		cartridge = "";
		deflecting = 0;
		cost = 1;
		timetolive = 2.5;
		typicalSpeed = 450;
		visibleFire = 0;	// how much is visible when this weapon is fired
		audibleFire = 0;
		airFriction = -0.005;
		simulation = "Shotshell";
		sideAirFriction = -0.001;
		caliber = 0.4;
	};
	
	class d3z_ammo_pel_dim : d3z_ammo_pel {
		model = "";
		tracerColor[] = {0, 0, 0, 0};
		tracerColorR[] = {0, 0, 0, 0};
		tracerStartTime = 0;
		tracerEndTime = 0;
		tracerScale = 0;
	};
};

class cfgmagazines {
	class ca_magazine;	// External class reference
	
	class d3z_buck_75_1 : ca_magazine {
		scope = public;
		displayName = "7.5 Shot Cartridge (1)";
		ammo = "d3z_ammo_shot";
		count = 2;
		initSpeed = 440;
		model = "d3z_shotguns\d3z_cartridge1.p3d";
		picture = "\d3z_shotguns\data\cartico.paa";
		descriptionShort = "Caliber: 12 gauge <br/>Rounds: 1 <br/>Used in: Shotgun";
	};
	
	class d3z_buck_75_2 : ca_magazine {
		scope = public;
		displayName = "7.5 Shot Cartridges (2)";
		ammo = "d3z_ammo_shot";
		count = 2;
		initSpeed = 440;
		model = "d3z_shotguns\d3z_cartridge2_mag.p3d";
		picture = "\d3z_shotguns\data\cartico.paa";
		descriptionShort = "Caliber: 12 gauge <br/>Rounds: 2 <br/>Used in: Shotgun";
	};
	

	
	class d3z_buck_75_1_dim : d3z_buck_75_1 {
		ammo = "d3z_ammo_shot_dim";
		displayName = "7.5 Shot Cartridge (1) dim";
	};
	
	class d3z_buck_75_2_dim : d3z_buck_75_2 {
		ammo = "d3z_ammo_shot_dim";
		displayName = "7.5 Shot Cartridges (2) dim";
	};
	
	class d3z_buck_75_5 : ca_magazine {
		scope = public;
		displayName = "7.5 Shot Cartridges (5)";
		ammo = "d3z_ammo_shot_2";
		count = 5;
		initSpeed = 440;
		model = "d3z_shotguns\d3z_cartridge1_mag.p3d";
		picture = "\CA\weapons\data\equip\M_12gauge_CA.paa";
		descriptionShort = "Caliber: 12 gauge <br/>Rounds: 5 <br/>Used in: Shotgun";
	};
	
	class d3z_buck_75_5_dim : d3z_buck_75_5 {
		displayName = "7.5 Shot Cartridges (5) dim";
		ammo = "d3z_ammo_shot_2_dim";
	};
};

class Mode_SemiAuto {};

class cfgweapons {
	class Rifle;	// External class reference
	
	class d3z_lanber : Rifle {
		scope = public;
		model = "d3z_shotguns\d3z_lanber";
		picture = "\d3z_shotguns\data\lanberpic.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		magazineReloadTime = 6;
		magazines[] = {"d3z_buck_75_2", "d3z_buck_75_2_dim", "d3z_buck_75_1", "d3z_buck_75_1_dim"};
		optics = true;
		modelOptics = "-";
		displayname = "FW Steiner";
		modes[] = {"Single"};
		distanceZoomMin = 50;
		distanceZoomMax = 50;
		
		class Single : Mode_SemiAuto {
			dispersion = 0;
			soundContinuous = 0;
			reloadTime = 0.15;
			reloadMagazineSound[] = {"\ca\sounds\weapons\rifles\M1014-reload", 0.316228, 1, 20};
			begin1[] = {"d3z_shotguns\s\shotx1a.wss", 2.37828, 1, 1000};
			begin2[] = {"d3z_shotguns\s\shotx2a.wss", 2.37828, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			drySound[] = {"ca\sounds\weapons\rifles\dry", 0.01, 1, 10};
			minRange = 0;
			minRangeProbab = 0.5;
			midRange = 60;
			midRangeProbab = 0.2;
			maxRange = 100;
			maxRangeProbab = 0.03;
			recoil = "recoil_shotgun";
			recoilProne = "recoil_shotgun";
		};
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons\data\Anim\M24.rtm"};
		
		class Library {
			libTextDesc = "Over/Under sporting shotgun, typically used for clay pigeon shooting and small birds.<br/>Fires a 7.5 shot cartridge.";
		};
		descriptionShort = "Over/Under sporting shotgun";
		cursor = "ShotgunCursor";
		cursoraim = "\ca\Weapons\Data\clear_empty";
	};
	
	class d3z_maxus : d3z_lanber {
		picture = "\d3z_shotguns\data\maxuspic.paa";
		model = "d3z_shotguns\d3z_maxus";
		displayname = "Browning Maxus";
		magazineReloadTime = 10;
		
		class Single : Mode_SemiAuto {
			dispersion = 0;
			soundContinuous = 0;
			reloadTime = 0.15;
			reloadMagazineSound[] = {"\ca\sounds\weapons\rifles\M1014-reload", 0.316228, 1, 20};
			begin1[] = {"d3z_shotguns\s\shot_maxus1.wss", 2.37828, 1, 1000};
			begin2[] = {"d3z_shotguns\s\shot_maxus2.wss", 2.37828, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			drySound[] = {"ca\sounds\weapons\rifles\dry", 0.01, 1, 10};
			minRange = 0;
			minRangeProbab = 0.5;
			midRange = 60;
			midRangeProbab = 0.2;
			maxRange = 100;
			maxRangeProbab = 0.03;
			recoil = "recoil_shotgun";
			recoilProne = "recoil_shotgun";
		};
		magazines[] = {"d3z_buck_75_5", "d3z_buck_75_5_dim", "d3z_buck_75_2", "d3z_buck_75_2_dim", "d3z_buck_75_1", "d3z_buck_75_1_dim"};
		
		class Library {
			libTextDesc = "Browning Maxus - claimed to be the world's best repeating shotgun.<br/>Fires a 7.5 shot cartridge.";
		};
		descriptionShort = "Browning Maxus";
	};
};

class cfgvehicles {
	class thing;	// External class reference
	class skeetdisk;	// External class reference
	
	class d3z_SkeetDisk : skeetdisk {
		armor = 1;
	};
	
	class d3z_cart : skeetdisk {
		model = "d3z_shotguns\d3z_cartridge1.p3d";
		airRotation = 0.2;
		timetolive = 30;
		airFriction2[] = {0.01, 0.01, 0.01};
		airFriction1[] = {0.01, 0.01, 0.01};
		airFriction0[] = {0.01, 0.01, 0.01};
	};
	class reammobox;	// External class reference
	
	class D3Z_Shotgunbox : reammobox {
		scope = public;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		displayName = "Local Basic Ammunition";
		model = "\ca\weapons\AmmoBoxes\LocalBasicAmmo.p3d";
		
		class TransportMagazines {
			class _xx_d3z_buck_75_5 {
				magazine = "d3z_buck_75_5";
				count = 80;
			};
			
			class _xx_d3z_buck_75_2 {
				magazine = "d3z_buck_75_2";
				count = 80;
			};
		};
		
		class TransportWeapons {
			class _xx_d3z_lanber {
				weapon = "d3z_lanber";
				count = 8;
			};
			
			class _xx_d3z_maxus {
				weapon = "d3z_maxus";
				count = 8;
			};
		};
	};
};

class cfgFunctions {
	class d3z {
		class Shotguns {
			class buckshot {
				description = "For Buckshot";
				file = "d3z_shotguns\z\buckshot_X.sqf";
			};
			
			class cartridge {
				description = "Cartridge Ejection";
				file = "d3z_shotguns\z\d3z_keys.sqf";
			};
		};
	};
};

class Extended_PostInit_EventHandlers {
	class d3z_shotgun_buckshot {
		init = "call compile preProcessFileLineNumbers 'd3z_shotguns\z\buckshot_init.sqf'";
	};
	
	class d3z_shotgun_cartridges {
		init = "[] spawn d3z_fnc_cartridge";
	};
};

class Extended_fired_EventHandlers {
	class CAManBase {
		d3z_pellets_fired = "_this spawn d3z_pellets";
	};
};
