// config.bin - 12:31:17 02/17/13, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

class CfgPatches {
	class KPFS_GSG9_E {
		units[] = {"KPFS_GSG9_Soldier_new"};
		weapons[] = {};
		requiredVersion = 1.56;
		requiredAddons[] = {"CACharacters2", "CACharacters_E", "KPFS_Weapons"};
	};
};

class CfgVehicles {
	class FR_R;	// External class reference
	
	class KPFS_GSG9_Soldier_new : FR_R {
		scope = public;
		vehicleClass = "kpfs_gsg9_new";
		languages[] = {"EN"};
		faceType = "HeadMask1Black";
		displayName = $STR_KPFS_GSG9_SOLDIER_NEW;
		model = "\kpfs_police_e\characters\gsg9\gsg_soldier_new";
		identityTypes[] = {"Head_DE", "Language_EN"};
		genericNames = "GermanMen";
		portrait = "\kpfs_police_e\data\portraits\combarhead_gsg9_new_ca.paa";
		icon = "\kpfs_police_e\data\ico\i_police_w_ca.paa";
		hiddenSelections[] = {"Camo01", "Camo02", "helmet"};
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\gsg9\gsg_soldier_co.paa", "\kpfs_police_e\characters\data\police_equip_co.paa", "\kpfs_police_e\characters\gsg9\gsg_helmet_co.paa"};
		magazines[] = {};
		backpack = "";
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		weaponSlots = "1	 + 	4	 + 12*		256	 + 2*	4096	 + 	2	 + 8*	16  + 12*131072";
		canHideBodies = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat", "kpfs_police_e\characters\gsg9\gsg_soldier.rvmat", "kpfs_police_e\characters\gsg9\gsg_soldier_wound1.rvmat", "kpfs_police_e\characters\gsg9\gsg_soldier_wound2.rvmat"};
		};
	};
	
	class KPFS_GSG9_Soldier_MP5_new : KPFS_GSG9_Soldier_new {
		scope = public;
		displayName = $STR_KPFS_GSG9_SOLDIER_MP5_NEW;
	};
	
	class KPFS_GSG9_Soldier_G36_new : KPFS_GSG9_Soldier_new {
		scope = public;
		displayName = $STR_KPFS_GSG9_SOLDIER_G36_NEW;
		weapons[] = {"G36_C_SD_eotech", "glock17_EP1", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_556x45_StanagSD", "30Rnd_556x45_StanagSD", "30Rnd_556x45_StanagSD", "30Rnd_556x45_StanagSD", "30Rnd_556x45_StanagSD", "30Rnd_556x45_StanagSD", "SmokeShell", "SmokeShell", "17Rnd_9x19_glock17", "17Rnd_9x19_glock17"};
		respawnWeapons[] = {"G36_C_SD_eotech"};
		respawnmagazines[] = {"30Rnd_556x45_StanagSD", "30Rnd_556x45_StanagSD"};
	};
	
	class KPFS_GSG9_Soldier_HK416_new : KPFS_GSG9_Soldier_new {
		scope = public;
		displayName = $STR_KPFS_GSG9_SOLDIER_HK416_NEW;
		weapons[] = {"KPFS_HK416_Aim", "glock17_EP1", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "SmokeShell", "SmokeShell", "17Rnd_9x19_glock17", "17Rnd_9x19_glock17"};
		respawnWeapons[] = {"KPFS_HK416_Aim"};
		respawnmagazines[] = {"20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag"};
	};
	
	class KPFS_GSG9_Soldier_Sniper_new : KPFS_GSG9_Soldier_new {
		scope = public;
		displayName = $STR_KPFS_GSG9_SOLDIER_SNIPER_NEW;
		weapons[] = {"VIL_HK416_Aim", "glock17_EP1", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag", "SmokeShell", "SmokeShell", "17Rnd_9x19_glock17", "17Rnd_9x19_glock17"};
		respawnWeapons[] = {"VIL_HK416_Aim"};
		respawnmagazines[] = {"20Rnd_556x45_Stanag", "20Rnd_556x45_Stanag"};
	};
	
	class KPFS_GSG9_Soldier_TL_new : KPFS_GSG9_Soldier_new {
		scope = public;
		displayName = $STR_KPFS_GSG9_SOLDIER_TL_NEW;
	};
	
	class KPFS_GSG9_Officer_new : KPFS_GSG9_Soldier_new {
		scope = public;
		displayName = $STR_KPFS_GSG9_OFFICER_NEW;
		weapons[] = {"glock17_EP1", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"17Rnd_9x19_glock17", "17Rnd_9x19_glock17"};
		respawnWeapons[] = {"glock17_EP1"};
		respawnmagazines[] = {"17Rnd_9x19_glock17", "17Rnd_9x19_glock17"};
	};
};
