// config.bin - 14:13:11 01/18/13, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define private		0
#define protected		1
#define public		2

class CfgPatches {
	class gsc_units_stalker_patch {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.0;
		requiredAddons[] = {};
	};
};

class CfgVehicleClasses {
	class gsc_stalker_class2 {
		displayName = "No Helmet/Cover";
	};
	
	class gsc_mil_class2 {
		displayName = "No Helmet/Cover";
	};
	
	class gsc_mil_class {
		displayName = "Helmet/Cover";
	};
	
	class gsc_stalker_class {
		displayName = "Helmet/Cover";
	};
};

class CfgFactionClasses {
	class gsc_stalker_faction {
		displayName = "GSC Stalker Units";
		priority = 100;
		side = 1;
	};
	
	class gsc_military_faction {
		displayName = "GSC Military Units";
		priority = 100;
		side = 1;
	};
};

class CfgVehicles {
	class All;	// External class reference
	class AllVehicles;	// External class reference
	class ThingEffect;	// External class reference
	class Land;	// External class reference
	class Man;	// External class reference
	class CAManBase;	// External class reference
	class RU_Soldier2;	// External class reference
	
	class gsc_military_helmet_wdl : RU_Soldier2 {
		scope = public;
		displayName = "Military 1";
		model = "\gsc_stalker\gsc_military_helmet_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_wdl_AT : RU_Soldier2 {
		scope = public;
		displayName = "Military 1 - AT";
		model = "\gsc_stalker\gsc_military_helmet_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_grey_AT : RU_Soldier2 {
		scope = public;
		displayName = "Military 2 - AT";
		model = "\gsc_stalker\gsc_military_helmet_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_wdlSNP : RU_Soldier2 {
		scope = public;
		displayName = "Military 1 - Sniper";
		model = "\gsc_stalker\gsc_military_helmet_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_greySNP : RU_Soldier2 {
		scope = public;
		displayName = "Military 2 - Sniper";
		model = "\gsc_stalker\gsc_military_helmet_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_helmet_grey : RU_Soldier2 {
		scope = public;
		displayName = "Military 2";
		model = "\gsc_stalker\gsc_military_helmet_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_grey : RU_Soldier2 {
		scope = public;
		displayName = "Military 2";
		model = "\gsc_stalker\gsc_military_head_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_greySNP : RU_Soldier2 {
		scope = public;
		displayName = "Military 2 - Sniper";
		model = "\gsc_stalker\gsc_military_head_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_wdlSNP : RU_Soldier2 {
		scope = public;
		displayName = "Military 1 - Sniper";
		model = "\gsc_stalker\gsc_military_head_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_wdl : RU_Soldier2 {
		scope = public;
		displayName = "Military 1";
		model = "\gsc_stalker\gsc_military_head_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_wdl_AT : RU_Soldier2 {
		scope = public;
		displayName = "Military 1 - AT";
		model = "\gsc_stalker\gsc_military_head_wdl.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_military_head_grey_AT : RU_Soldier2 {
		scope = public;
		displayName = "Military 2 - AT";
		model = "\gsc_stalker\gsc_military_head_grey.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_mil_class2";
		faction = "gsc_military_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\military.rvmat", "gsc_stalker\military_wound1.rvmat", "gsc_stalker\military_wound2.rvmat"};
		};
	};
	
	class gsc_scientist1 : RU_Soldier2 {
		scope = public;
		displayName = "Scientist 1";
		model = "\gsc_stalker\gsc_eco_suit.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\scien.rvmat", "gsc_stalker\scien_wound1.rvmat", "gsc_stalker\scien_wound2.rvmat"};
		};
	};
	
	class gsc_scientist1_head : RU_Soldier2 {
		scope = public;
		displayName = "Scientist 1";
		model = "\gsc_stalker\gsc_eco_suit_head.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\scien.rvmat", "gsc_stalker\scien_wound1.rvmat", "gsc_stalker\scien_wound2.rvmat"};
		};
	};
	
	class gsc_scientist2 : RU_Soldier2 {
		scope = public;
		displayName = "Scientist 2";
		model = "\gsc_stalker\gsc_eco_suit2.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\scien.rvmat", "gsc_stalker\scien_wound1.rvmat", "gsc_stalker\scien_wound2.rvmat"};
		};
	};
	
	class gsc_scientist2_head : RU_Soldier2 {
		scope = public;
		displayName = "Scientist 2";
		model = "\gsc_stalker\gsc_eco_suit2_head.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\scien.rvmat", "gsc_stalker\scien_wound1.rvmat", "gsc_stalker\scien_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_mask_fred : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Flecktarn";
		model = "\gsc_stalker\gsc_eco_stalker_mask_fred.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_head_fred : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Flecktarn";
		model = "\gsc_stalker\gsc_eco_stalker_head_fred.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_mask_camo : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Camo";
		model = "\gsc_stalker\gsc_eco_stalker_mask_camo.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_head_camo1 : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Camo";
		model = "\gsc_stalker\gsc_eco_stalker_head_camo1.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_cloth_loner_head : RU_Soldier2 {
		scope = public;
		displayName = "Loner";
		model = "\gsc_stalker\gsc_cloth_loner_head.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {};
		};
	};
	
	class gsc_eco_stalker_mask_duty : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Black";
		model = "\gsc_stalker\gsc_eco_stalker_mask_duty.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_head_duty : RU_Soldier2 {
		scope = public;
		displayName = "Stalker - Black";
		model = "\gsc_stalker\gsc_eco_stalker_head_duty.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_mask_neutral : RU_Soldier2 {
		scope = public;
		displayName = "Stalker";
		model = "\gsc_stalker\gsc_eco_stalker_mask.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
	
	class gsc_eco_stalker_head_neutral : RU_Soldier2 {
		scope = public;
		displayName = "Stalker";
		model = "\gsc_stalker\gsc_eco_stalker_head.p3d";
		identityTypes[] = {"Head_RU"};
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnMagazines[] = {};
		weaponSlots = 1	+ 4	+ 12*	256	+ 2*	4096	+ 2	+ 8*	16 + 12*131072;
		canCarryBackPack = 1;
		canHideBodies = true;
		vehicleClass = "gsc_stalker_class2";
		faction = "gsc_stalker_faction";
		picture = "\Ca\characters\data\Ico\i_null_CA.paa";
		icon = "\Ca\characters2\data\icon\i_soldier_CA.paa";
		side = 1;
		
		class Wounds {
			tex[] = {};
			mat[] = {"gsc_stalker\stalker.rvmat", "gsc_stalker\stalker_wound1.rvmat", "gsc_stalker\stalker_wound2.rvmat"};
		};
	};
};
