// config.bin - 02:48:49 02/16/13, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

class CfgPatches {
	class KPFS_Weapons {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.0;
		requiredAddons[] = {"CAWeapons"};
	};
};

class CfgRecoils {
	p22x[] = {0.04, 0.006*( (5/7)), 0.05*.5*( (5/7)), 0.01, 0.009*( (5/7)), 0, 0.045, 0, -0.025*.5*( (5/7))};
	p226[] = {0.04, 0.006*( (5/7)), 0.05*.5*( (5/7)), 0.01, 0.009*( (5/7)), 0, 0.045, 0, -0.025*.5*( (5/7))};
};
class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference
class Mode_FullAuto;	// External class reference

class CfgWeapons {
	class Default;	// External class reference
	class glock17_EP1;	// External class reference
	
	class kpfs_glock17 : glock17_EP1 {
		model = "\kpfs_weapons\glock.p3d";
		picture = "\kpfs_weapons\data\icons\w_glock_ca.paa";
		displayName = $STR_KPFS_GLOCK;
		
		class Armory {
			author = "$STR_AUTHOR_VILAs";
		};
	};
	class Colt1911;	// External class reference
	
	class KPFS_P52 : Colt1911 {
		scope = public;
		displayName = $STR_KPFS_P52;
		
		class Library {
			libTextDesc = $STR_KPFS_LIB_P52;
		};
	};
};

class cfgVehicles {
	class ReammoBox;	// External class reference
	
	class KPFS_WeaponBox : ReammoBox {
		scope = public;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		displayName = $STR_KPFS_WEAPONBOX;
		model = "\ca\weapons\AmmoBoxes\USBasicAmmo.p3d";
		
		class TransportMagazines {
			class _xx_20Rnd_762x51_FNFAL {
				magazine = "20Rnd_762x51_FNFAL";
				count = 20;
			};
			
			class _xx_KPFS_30Rnd_762x43_STG44 {
				magazine = "KPFS_30Rnd_762x43_STG44";
				count = 20;
			};
			
			class _xx_20Rnd_762x51_DMR {
				magazine = "20Rnd_762x51_DMR";
				count = 20;
			};
			
			class _xx_30Rnd_762x39_AK47 {
				magazine = "30Rnd_762x39_AK47";
				count = 20;
			};
			
			class _xx_30Rnd_556x45_Stanag {
				magazine = "30Rnd_556x45_Stanag";
				count = 400;
			};
			
			class _xx_KPFS_KPFS_120Rnd_MG1 {
				magazine = "KPFS_120Rnd_MG1";
				count = 50;
			};
			
			class _xx_KPFS_32Rnd_MP2 {
				magazine = "KPFS_32Rnd_MP2";
				count = 20;
			};
			
			class _xx_KPFS_25Rnd_pm {
				magazine = "KPFS_25Rnd_pm";
				count = 20;
			};
			
			class _xx_KPFS_10Rnd_PSL {
				magazine = "KPFS_10Rnd_PSL";
				count = 20;
			};
			
			class _xx_KPFS_100Rnd_762x39_RPD {
				magazine = "KPFS_100Rnd_762x39_RPD";
				count = 50;
			};
			
			class _xx_KPFS_10Rnd_762x39_SKS {
				magazine = "KPFS_10Rnd_762x39_SKS";
				count = 20;
			};
		};
		
		class TransportWeapons {
			class _xx_KPFS_G1 {
				weapon = KPFS_G1;
				count = 1;
			};
			
			class _xx_KPFS_G3SG1 {
				weapon = KPFS_G3SG1;
				count = 1;
			};
			
			class _xx_kpfs_G3a3 {
				weapon = "kpfs_G3a3";
				count = 1;
			};
			
			class _xx_kpfs_g3a2 {
				weapon = "kpfs_g3a2";
				count = 1;
			};
			
			class _xx_kpfs_g3a4 {
				weapon = "kpfs_g3a4";
				count = 1;
			};
			
			class _xx_kpfs_hk32 {
				weapon = "kpfs_hk32";
				count = 1;
			};
			
			class _xx_KPFS_HK416_Aim {
				weapon = "KPFS_HK416_Aim";
				count = 1;
			};
			
			class _xx_kpfs_KPFS_MG1 {
				weapon = KPFS_MG1;
				count = 1;
			};
			
			class _xx_KPFS_MP2 {
				weapon = KPFS_MP2;
				count = 1;
			};
			
			class _xx_KPFS_MP2A1 {
				weapon = KPFS_MP2A1;
				count = 1;
			};
			
			class _xx_KPFS_MP5A3SD {
				weapon = KPFS_MP2A1;
				count = 1;
			};
			
			class _xx_KPFS_MP5A3 {
				weapon = KPFS_MP5A3;
				count = 1;
			};
			
			class _xx_KPFS_MPi_KMKIX {
				weapon = "KPFS_MPi_KMKIX";
				count = 1;
			};
			
			class _xx_KPFS_PM63 {
				weapon = KPFS_PM63;
				count = 1;
			};
			
			class _xx_KPFS_PSL {
				weapon = KPFS_PSL;
				count = 1;
			};
			
			class _xx_KPFS_KarS {
				weapon = "KPFS_KarS";
				count = 1;
			};
			
			class _xx_KPFS_MP4 {
				weapon = KPFS_MP4;
				count = 1;
			};
		};
	};
	
	class KPFS_PistolBox : KPFS_WeaponBox {
		displayName = $STR_KPFS_PISTOLBOX;
		model = "\ca\weapons\AmmoBoxes\USOrdnance.p3d";
		
		class TransportMagazines {
			class _xx_Mine_DM11 {
				magazine = "Mine_DM11";
				count = 10;
			};
			
			class _xx_HandGrenade_dm41 {
				magazine = "HandGrenade_dm41";
				count = 50;
			};
			
			class _xx_kpfs_8Rnd_9x17 {
				magazine = "kpfs_8Rnd_9x17";
				count = 20;
			};
			
			class _xx_KPFS_8Rnd_9x19_P5 {
				magazine = "KPFS_8Rnd_9x19_P5";
				count = 20;
			};
			
			class _xx_KPFS_8Rnd_762x25_TT33 {
				magazine = "KPFS_8Rnd_762x25_TT33";
				count = 20;
			};
			
			class _xx_kpfs_kpfs_15Rnd_9x19 {
				magazine = "kpfs_15Rnd_9x19";
				count = 20;
			};
			
			class _xx_kpfs_9Rnd_9x19 {
				magazine = "kpfs_9Rnd_9x19";
				count = 20;
			};
			
			class _xx_KPFS_16Rnd_9x19_para {
				magazine = "KPFS_16Rnd_9x19_para";
				count = 20;
			};
			
			class _xx_kpfs_15Rnd_9x19_M9 {
				magazine = "15Rnd_9x19_M9";
				count = 20;
			};
			
			class _xx_KPFS_8Rnd_9x19_P1 {
				magazine = "KPFS_8Rnd_9x19_P1";
				count = 20;
			};
			
			class _xx_KPFS_15Rnd_9x19_P8 {
				magazine = "KPFS_15Rnd_9x19_P8";
				count = 20;
			};
			
			class _xx_kpfs_8Rnd_9x19 {
				magazine = "kpfs_8Rnd_9x19";
				count = 20;
			};
		};
		
		class TransportWeapons {
			class _xx_KPFS_HK4 {
				weapon = KPFS_HK4;
				count = 1;
			};
			
			class _xx_kpfs_glock17 {
				weapon = "kpfs_glock17";
				count = 1;
			};
			
			class _xx_KPFS_KPFS_P52 {
				weapon = KPFS_P52;
				count = 1;
			};
			
			class _xx_KPFS_P5 {
				weapon = KPFS_P5;
				count = 1;
			};
			
			class _xx_KPFS_HKP7 {
				weapon = KPFS_HKP7;
				count = 1;
			};
			
			class _xx_KPFS_P8 {
				weapon = KPFS_P8;
				count = 1;
			};
			
			class _xx_KPFS_HKP30 {
				weapon = KPFS_HKP30;
				count = 1;
			};
			
			class _xx_KPFS_P1 {
				weapon = KPFS_P1;
				count = 1;
			};
			
			class _xx_KPFS_P88 {
				weapon = KPFS_P88;
				count = 1;
			};
			
			class _xx_KPFS_P99QA {
				weapon = KPFS_P99QA;
				count = 1;
			};
			
			class _xx_KPFS_P220 {
				weapon = KPFS_P220;
				count = 1;
			};
			
			class _xx_KPFS_KPFS_P225 {
				weapon = KPFS_KPFS_P225;
				count = 1;
			};
			
			class _xx_KPFS_P226 {
				weapon = KPFS_P226;
				count = 1;
			};
			
			class _xx_KPFS_P2000 {
				weapon = KPFS_P2000;
				count = 1;
			};
			
			class _xx_KPFS_TT33 {
				weapon = KPFS_TT33;
				count = 1;
			};
		};
	};
};
