// config.bin - 13:09:51 02/17/13, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

class CfgPatches {
	class KPFS_german_police_E {
		units[] = {"KPFS_Policeman_new"};
		weapons[] = {};
		requiredVersion = 1.56;
		requiredAddons[] = {"CACharacters2", "CACharacters_E", "KPFS_Weapons"};
	};
};

class CfgVehicleClasses {
	class kpfs_police_new {
		displayName = $STR_KPFS_POLICE_NEW;
	};
	
	class kpfs_police_vest_new {
		displayName = $STR_KPFS_POLICE_VEST_NEW;
	};
	
	class kpfs_federal_police {
		displayName = $STR_KPFS_FEDERAL_POLICE;
	};
	
	class kpfs_police_car_new {
		displayName = $STR_KPFS_POLICE_CAR_NEW;
	};
	
	class kpfs_police_air {
		displayName = $STR_KPFS_POLICE_AIR;
	};
	
	class kpfs_police_special {
		displayName = $STR_KPFS_POLICE_SPECIAL;
	};
	
	class kpfs_gsg9_new {
		displayName = $STR_KPFS_GSG9_MEN_NEW;
	};
	
	class kpfs_vpk_ddr {
		displayName = $STR_KPFS_VPK_MEN_DDR;
	};
};

class CfgVehicles {
	class Policeman;	// External class reference
	
	class KPFS_Policeman_new : Policeman {
		scope = protected;
		faction = BIS_GER;
		vehicleClass = "kpfs_police_new";
		languages[] = {"EN"};
		displayName = $STR_KPFS_POLICEMAN;
		model = "\kpfs_police_e\characters\pol_hh_blue";
		identityTypes[] = {"Head_DE", "pilot_sunglasses", "Civ_Glasses"};
		genericNames = "GermanMen";
		portrait = "\Ca\characters\data\portraits\comBarHead_common_officer_ca.paa";
		icon = "\kpfs_police_e\data\ico\i_police_w_ca.paa";
		hiddenSelections[] = {"Camo01", "Camo02"};
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhh\pol_blue_sh_co.paa", "\kpfs_police_e\characters\mhh\pol_blue_sh_hat_co.paa"};
		weapons[] = {KPFS_P99QA};
		magazines[] = {"KPFS_16Rnd_9x19_para", "KPFS_16Rnd_9x19_para"};
		respawnWeapons[] = {KPFS_P99QA};
		respawnmagazines[] = {"KPFS_16Rnd_9x19_para", "KPFS_16Rnd_9x19_para"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat", "kpfs_police_e\characters\mhh\pol_blue.rvmat", "kpfs_police_e\characters\mhh\pol_blue_wound1.rvmat", "kpfs_police_e\characters\mhh\pol_blue_wound2.rvmat"};
		};
	};
	
	class KPFS_Policeman_hh_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_HH;
		portrait = "\kpfs_police_e\data\portraits\comBarHead_police_hh_ca";
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhh\pol_blue_hh_co.paa", "\kpfs_police_e\characters\mhh\pol_blue_hh_hat_co.paa"};
	};
	
	class KPFS_Policeman_sh_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_SH;
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhh\pol_blue_sh_co.paa", "\kpfs_police_e\characters\mhh\pol_blue_sh_hat_co.paa"};
	};
	
	class KPFS_Policeman_hb_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_HB;
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhh\pol_blue_hb_co.paa", "\kpfs_police_e\characters\mhh\pol_blue_hb_hat_co.paa"};
	};
	
	class KPFS_Policeman_ni_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_NI;
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhh\pol_blue_nds_co.paa", "\kpfs_police_e\characters\mhh\pol_blue_nds_hat_co.paa"};
		weapons[] = {KPFS_P2000};
		magazines[] = {"KPFS_13Rnd_9x19_P2000", "KPFS_13Rnd_9x19_P2000", "KPFS_13Rnd_9x19_P2000", "KPFS_13Rnd_9x19_P2000"};
		respawnWeapons[] = {KPFS_P2000};
		respawnmagazines[] = {"KPFS_13Rnd_9x19_P2000", "KPFS_13Rnd_9x19_P2000"};
	};
	
	class KPFS_Policeman_mv_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_MV;
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhh\pol_blue_mv_co.paa", "\kpfs_police_e\characters\mhh\pol_blue_mv_hat_co.paa"};
	};
	
	class KPFS_Policeman_he_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_HE;
		model = "\kpfs_police_e\characters\pol_he_blue";
		portrait = "\kpfs_police_e\data\portraits\comBarHead_police_he_ca.paa";
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhe\pol_blue_he_co.paa", "\kpfs_police_e\characters\mhe\pol_white_he_hat_co.paa"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat", "kpfs_police_e\characters\mhe\pol_blue.rvmat", "kpfs_police_e\characters\mhe\pol_blue_wound1.rvmat", "kpfs_police_e\characters\mhe\pol_blue_wound2.rvmat"};
		};
	};
	
	class KPFS_Policeman_rp_new : KPFS_Policeman_he_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_RP;
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhe\pol_blue_rp_co.paa", "\kpfs_police_e\characters\mhe\pol_white_rp_hat_co.paa"};
	};
	
	class KPFS_Policeman_th_new : KPFS_Policeman_he_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_TH;
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhe\pol_blue_th_co.paa", "\kpfs_police_e\characters\mhe\pol_white_th_hat_co.paa"};
	};
	
	class KPFS_Policeman_sa_new : KPFS_Policeman_he_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_SA;
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mhe\pol_blue_sa_co.paa", "\kpfs_police_e\characters\mhe\pol_white_sa_hat_co.paa"};
	};
	
	class KPFS_Policeman_nrw_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_NRW;
		model = "\kpfs_police_e\characters\pol_nrw_blue";
		portrait = "\kpfs_police_e\data\portraits\comBarHead_police_nrw_ca.paa";
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mnrw\pol_blue_nrw_co.paa", "\kpfs_police_e\characters\mnrw\pol_white_nrw_hat_co.paa"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat", "kpfs_police_e\characters\mnrw\pol_blue.rvmat", "kpfs_police_e\characters\mnrw\pol_blue_wound1.rvmat", "kpfs_police_e\characters\mnrw\pol_blue_wound2.rvmat"};
		};
	};
	
	class KPFS_Policeman_bw_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_BW;
		model = "\kpfs_police_e\characters\pol_bw_blue";
		portrait = "\kpfs_police_e\data\portraits\comBarHead_police_bw_ca.paa";
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mbw\pol_blue_bw_co.paa", "\kpfs_police_e\characters\mbw\pol_white_bw_hat_co.paa"};
		weapons[] = {KPFS_P2000};
		magazines[] = {"KPFS_13Rnd_9x19_P2000", "KPFS_13Rnd_9x19_P2000", "KPFS_13Rnd_9x19_P2000", "KPFS_13Rnd_9x19_P2000"};
		respawnWeapons[] = {KPFS_P2000};
		respawnmagazines[] = {"KPFS_13Rnd_9x19_P2000", "KPFS_13Rnd_9x19_P2000"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat", "kpfs_police_e\characters\mbw\pol_blue.rvmat", "kpfs_police_e\characters\mbw\pol_blue_wound1.rvmat", "kpfs_police_e\characters\mbw\pol_blue_wound2.rvmat"};
		};
	};
	
	class KPFS_Policeman_bb_new : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_BB;
		model = "\kpfs_police_e\characters\pol_bb_blue";
		portrait = "\kpfs_police_e\data\portraits\comBarHead_police_bb_ca.paa";
		hiddenSelections[] = {"Camo01", "Camo03", "camo02", "berlin", "sn"};
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mbb\pol_blue_bb_co.paa", "\kpfs_police_e\characters\mbb\pol_blue_bb_hat_co.paa"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat", "kpfs_police_e\characters\mbb\pol_blue.rvmat", "kpfs_police_e\characters\mbb\pol_blue_wound1.rvmat", "kpfs_police_e\characters\mbb\pol_blue_wound2.rvmat"};
		};
	};
	
	class KPFS_Policeman_b_new : KPFS_Policeman_bb_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_B;
		hiddenSelections[] = {"Camo01", "Camo03", "camo02", "bb", "sn"};
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mbb\pol_blue_b_co.paa", "\kpfs_police_e\characters\mbb\pol_blue_b_hat_co.paa"};
	};
	
	class KPFS_Policeman_sn_new : KPFS_Policeman_bb_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_SN;
		hiddenSelections[] = {"Camo01", "Camo02", "camo03", "bb", "berlin"};
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mbb\pol_blue_sn_co.paa", "\kpfs_police_e\characters\mbb\pol_blue_sn_hat_co.paa"};
	};
	
	class KPFS_Policeman_by_leather : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_BY;
		model = "\kpfs_police_e\characters\pol_by_green";
		portrait = "\kpfs_police_e\data\portraits\comBarHead_police_by_ca.paa";
		hiddenSelections[] = {"Camo01", "Camo02", "kokarde"};
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mno\pol_green_by_co.paa", "\kpfs_police_e\characters\mno\pol_green_by_hat_co.paa"};
		weapons[] = {KPFS_HKP7};
		magazines[] = {"kpfs_8Rnd_9x19", "kpfs_8Rnd_9x19"};
		respawnWeapons[] = {KPFS_HKP7};
		respawnmagazines[] = {"kpfs_8Rnd_9x19", "kpfs_8Rnd_9x19"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat", "kpfs_police_e\characters\mno\pol_green.rvmat", "kpfs_police_e\characters\mno\pol_green_wound1.rvmat", "kpfs_police_e\characters\mno\pol_green_wound2.rvmat"};
		};
	};
	
	class KPFS_Policeman_sl_leather : KPFS_Policeman_by_leather {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_SL;
		hiddenSelections[] = {"Camo01", "Camo02"};
		hiddenSelectionsTextures[] = {"\kpfs_police_e\characters\mno\pol_green_sl_co.paa", "\kpfs_police_e\characters\mno\pol_green_sl_hat_co.paa"};
		weapons[] = {KPFS_P225};
		magazines[] = {"kpfs_15Rnd_9x19", "kpfs_15Rnd_9x19"};
		respawnWeapons[] = {KPFS_P225};
		respawnmagazines[] = {"kpfs_15Rnd_9x19", "kpfs_15Rnd_9x19"};
	};
	
	class KPFS_Policeman_bp : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_BP;
		vehicleClass = "kpfs_federal_police";
		model = "\kpfs_police_e\characters\bpol_blue";
		portrait = "\kpfs_police_e\data\portraits\comBarHead_bpol_ca.paa";
		weapons[] = {KPFS_HKP30};
		magazines[] = {"15Rnd_9x19_M9", "15Rnd_9x19_M9"};
		respawnWeapons[] = {KPFS_HKP30};
		respawnmagazines[] = {"15Rnd_9x19_M9", "15Rnd_9x19_M9"};
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
	};
	
	class KPFS_Policeman_bpo : KPFS_Policeman_new {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_BPO;
		vehicleClass = "kpfs_federal_police";
		model = "\kpfs_police_e\characters\bp\bp_officer";
		portrait = "\kpfs_police_e\data\portraits\comBarHead_bp_officer_ca.paa";
		weapons[] = {};
		magazines[] = {};
		respawnWeapons[] = {};
		respawnmagazines[] = {};
		hiddenSelections[] = {};
		hiddenSelectionsTextures[] = {};
	};
};
 