// config.bin - 03:50:09 01/18/13, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

class CfgPatches {
	class GLT_Objects {
		units[] = {"glt_billboard_big", "glt_billboard_narrow", "glt_mapstand", "glt_roadsign_octagon", "glt_roadsign_rectangle", "glt_roadsign_round", "glt_roadsign_square", "glt_roadsign_triangle", "glt_stand_sign", "glt_wallmount_40x120", "glt_wallmount_150x50", "glt_wallmount_300x90"};
		weapons[] = {};
	};
};

class CfgVehicleClasses {
	class GLT_Objects {
		displayName = "GLT - Objects";
	};
};

class cfgVehicles {
	class FlagCarrier;	// External class reference
	
	class glt_mapstand : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_mapstand.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Map Board";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\chernarus_map.paa"};
	};
	
	class glt_roadsign_octagon : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_roadsign_octagon.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Road sign octa";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Display"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\stop_new_co.paa"};
	};
	
	class glt_roadsign_rectangle : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_roadsign_rectangle.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Road sign rect";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Display"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\parkoviste_new_co.paa"};
	};
	
	class glt_roadsign_round : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_roadsign_round.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Road sign round";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Display"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\celnice_co.paa"};
	};
	
	class glt_roadsign_square : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_roadsign_square.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Road sign square";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Display"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\slepa_co.paa"};
	};
	
	class glt_roadsign_triangle : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_roadsign_triangle.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Road sign triangle";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Display"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\deti_new_co.paa"};
	};
	
	class glt_stand_sign : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_stand_sign.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Stand Sign";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"side1", "side2"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\danger.paa", "\glt_signs\tex\danger.paa"};
	};
	
	class glt_wallmount_40x120 : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_wallmount_40x120.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Wallmounted 40x120";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\sign40x120_co.paa"};
	};
	
	class glt_wallmount_150x50 : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_wallmount_150x50.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Wallmounted 150x50";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\sign150x50_co.paa"};
	};
	
	class glt_wallmount_300x90 : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_wallmount_300x90.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "GLT_Objects";
		displayName = "Wallmounted 300x90";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\tex\sign300x90_co.paa"};
	};
	
	class glt_billboard_big : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_billboard_big.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "Banner_groﬂ_1";
		displayName = "Billboard big";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\posters\wide_poster_01.paa"};
	};
	
		class glt_billboard_big2 : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_billboard_big.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "Banner_groﬂ_2";
		displayName = "Billboard big";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\posters\wide_poster_02.paa"};
	};
	
		class glt_billboard_big3 : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_billboard_big.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "Banner_groﬂ_3";
		displayName = "Billboard big";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\posters\wide_poster_03.paa"};
	};
	
	class glt_billboard_narrow : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_billboard_narrow.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "Banner_mittel_1";
		displayName = "Billboard narrow";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\posters\narrow_poster_01.paa"};
	};

	class glt_billboard_narrow2 : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_billboard_narrow.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "Banner_mittel_2";
		displayName = "Billboard narrow";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\posters\narrow_poster_02.paa"};
	};
	
	class glt_billboard_narrow3 : FlagCarrier {
		scope = public;
		model = "\glt_signs\glt_billboard_narrow.p3d";
		icon = "\ca\data\data\Unknown_object.paa";
		vehicleClass = "Banner_mittel_3";
		displayName = "Billboard narrow";
		mapSize = 0.7;
		accuracy = 0.2;	// accuracy needed to recognize type of this target
		destrType = "DestructNo";
		hiddenSelections[] = {"Poster"};
		hiddenSelectionsTextures[] = {"\glt_signs\posters\narrow_poster_03.paa"};
	};
};
