// config.bin - 01:52:59 02/16/13, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

class CfgPatches {
	class KPFS_german_police_vest_des {
		units[] = {"KPFS_Policeman_vest_des"};
		weapons[] = {};
		requiredVersion = 1.6;
		requiredAddons[] = {"CACharacters2", "CACharacters_E"};
	};
};

class CfgVehicleClasses {
	class kpfs_police_vest_des {
		displayName = $STR_KPFS_POLICE_VEST_DES;
	};
	
	class kpfs_police_car_des {
		displayName = $STR_KPFS_POLICE_CAR_DES;
	};
};

class CfgVehicles {
	class Policeman;	// External class reference
	
	class KPFS_Policeman_vest_des : Policeman {
		scope = public;
		faction = BIS_GER;
		vehicleClass = "kpfs_police_vest_des";
		languages[] = {"EN"};
		displayName = $STR_KPFS_POLICEMAN_VEST_DES;
		model = "\kpfs_police_des\officer_pol_des";
		identityTypes[] = {"pilot_sunglasses", "Civ_Glasses"};
		genericNames = "GermanMen";
		portrait = "\kpfs_police_des\data\portraits\combarhead_police_des_ca";
		icon = "\kpfs_police_des\data\ico\i_police_w_ca.paa";
		weapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat", "kpfs_police_des\characters\pol_desert_vest.rvmat", "kpfs_police_des\characters\pol_desert_vest_wound1.rvmat", "kpfs_police_des\characters\pol_desert_vest_wound2.rvmat"};
		};
	};
	
	class KPFS_Policeman_vest_des_cap : KPFS_Policeman_vest_des {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_VEST_DES_CAP;
		portrait = "\kpfs_police_des\data\portraits\combarhead_police_cap_des_ca";
		model = "\kpfs_police_des\operator_pol_des";
		weapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
	};
	
	class KPFS_Policeman_vest_des_beret : KPFS_Policeman_vest_des {
		scope = public;
		displayName = $STR_KPFS_POLICEMAN_VEST_DES_BERET;
		portrait = "\kpfs_police_des\data\portraits\combarhead_police_officer_des_ca";
		model = "\kpfs_police_des\officer_pol_des_beret";
		weapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
	};
};
