// config.bin - 19:00:35 02/03/13, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define VSoft		0
#define VArmor		1
#define VAir		2

class CfgPatches {
	class dpv {
		units[] = {"dpv", "dpv_green", "dpv_black"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"CAData", "CACharacters2", "CAWeapons", "CAWeapons2", "CASounds", "CA_Anims_Char"};
	};
};

class CfgMovesBasic {
	class DefaultDie;	// External class reference
	
	class ManActions {
		dpv_Driver = "dpv_Driver";
		dpv_CoDriver = "dpv_CoDriver";
		dpv_gunner = "dpv_gunner";
	};
};

class CfgMovesMaleSdr : CfgMovesBasic {
	class States {
		class dpv_Dead : DefaultDie {
			actions = "DeadActions";
			file = "\dpv\anim\dpv_Driver.rtm";
			speed = 0.5;
			looped = false;
			terminal = true;
			soundEnabled = false;
			connectTo[] = {"DeadState", 0.1};
		};
		class Crew;	// External class reference
		
		class dpv_Driver : Crew {
			file = "\dpv\anim\dpv_Driver.rtm";
			interpolateTo[] = {"Bike_Dead", 1};
		};
		
		class dpv_CoDriver : Crew {
			file = "\dpv\anim\dpv_codriver.rtm";
			interpolateTo[] = {"dpv_Dead", 1};
		};
		
		class dpv_gunner : Crew {
			file = "\dpv\anim\dpv_gunner.rtm";
			interpolateTo[] = {"dpv_Dead", 1};
		};
	};
};
class WeaponFireGun;	// External class reference
class WeaponCloudsGun;	// External class reference
class WeaponFireMGun;	// External class reference
class WeaponCloudsMGun;	// External class reference
class NewTurret;	// External class reference
class ViewOptics;	// External class reference
class ViewPilot;	// External class reference
class HeadLimits;	// External class reference
class Sounds;	// External class reference
class HitPoints;	// External class reference
class Turrets;	// External class reference
class mainTurret;	// External class reference
class CommanderOptics;	// External class reference
class DefaultEventhandlers;	// External class reference

class CfgVehicles {
	class Land;	// External class reference
	
	class LandVehicle : Land {
		class NewTurret;	// External class reference
		class ViewPilot;	// External class reference
		class Sounds;	// External class reference
	};
	
	class Car : LandVehicle {
		class Sounds : Sounds {
			class Engine;	// External class reference
			class Movement;	// External class reference
		};
		
		class Eventhandlers : DefaultEventhandlers {};
	};
	
	class dpv : Car {
		expansion = 1;
		htMin = 60;
		htMax = 1800;
		afMax = 200;
		mfMax = 100;
		mFact = 0;
		tBody = 0;
		scope = public;
		accuracy = 1.0;	// accuracy needed to recognize type of this target
		side = TWest;
		faction = BIS_US;
		Model = "\dpv\dpv.p3d";
		Picture = "\dpv\data\dpv_picture.paa";
		Icon = "\dpv\Data\dpv_mapicon.paa";
		mapSize = 5;
		displayName = "Chenowth DPV Desert LRPV";
		vehicleClass = "Car";
		crew = "US_Soldier_EP1";
		typicalCargo[] = {"US_Soldier_EP1", "US_Soldier_EP1"};
		damperSize = 0.25;	// max. damper amplitude
		damperForce = 1.2;	// larger number more stiffness dampers
		damperDamping = 3;	// larger number less movement in dampers
		armor = 50;
		damageResistance = 0.0862;
		terrainCoef = 0.0;
		maxspeed = 500.0;	// max speed on level road, km/h
		steerAheadPlan = 0.2;
		turnCoef = 2.0;
		predictTurnPlan = 1;
		enableGPS = 0;
		type = VArmor;
		cost = 100000;
		armorGlass = 0.5;
		armorWheels = 0.1;
		nameSound = "ambulance";
		transportRepair = 200000000;
		transportAmmo = 300000;
		transportFuel = 3000;
		supplyRadius = 7.5;
		attendant = true;
		transportMaxWeapons = 10;
		transportMaxMagazines = 30;
		soundServo[] = {"\Ca\sounds\Vehicles\Servos\turret-1", db-40, 1.0, 10};
		soundEnviron[] = {"", db-5, 1};
		transportSoldier = 0;
		gearBox[] = {-8, 0, 10, 6.15, 4.44, 3.33, 2.0, 1.0};
		fuelCapacity = 100;
		
		class Turrets : Turrets {
			class MainTurret : mainTurret {
				body = "mainTurret";
				gun = "mainGun";
				weapons[] = {"M2"};
				magazines[] = {"100Rnd_127x99_M2"};
				soundServo[] = {"\Ca\sounds\Vehicles\Servos\turret-1", db-40, 1.0, 10};
				primaryGunner = 1;
				gunnerName = "M2";
				commanding = 1;
				minElev = -15;
				maxElev = 30;
				minTurn = -30;
				maxTurn = 30;
				gunnerAction = "dpv_Gunner";
				viewGunnerInExternal = true;
				castGunnerShadow = true;
				stabilizedInAxes = "StabilizedInAxesBoth";
				
				class ViewOptics {
					initAngleX = 0;
					minAngleX = -30;
					maxAngleX = 30;
					initAngleY = 0;
					minAngleY = -100;
					maxAngleY = 100;
					initFov = 0.455;
					minFov = 0.25;
					maxFov = 0.7;
				};
				gunBeg = "usti hlavne";	// endpoint of the gun
				gunEnd = "konec hlavne";	// chamber of the gun
				memoryPointsGetInGunner = "pos gunner";
				memoryPointsGetInGunnerDir = "pos gunner dir";
				memoryPointGun = "usti hlavne";
				memoryPointGunnerOptics = "gunnerview";
			};
			
			class PassangerGun : MainTurret {
				startengine = false;
				body = "Turret_2";
				gun = "Gun_2";
				animationSourceBody = "Turret_2";
				animationSourceGun = "Gun_2";
				animationSourceHatch = "";
				selectionFireAnim = "zasleh_2";
				proxyIndex = 2;
				gunnerName = "M249 SAW";
				commanding = -2;
				minTurn = -50;
				maxTurn = 50;
				initTurn = 0;
				weapons[] = {M249};
				magazines[] = {"200Rnd_556x45_M249"};
				gunBeg = "usti hlavne_2";	// endpoint of the gun
				gunEnd = "konec hlavne_2";	// chamber of the gun
				gunnerAction = "HMMWV_Driver";
				primaryGunner = 0;
				memoryPointsGetInGunner = "pos codriver";
				memoryPointsGetInGunnerDir = "pos codriver dir";
				memoryPointGun = "usti hlavne_2";
				memoryPointGunnerOptics = "gunnerview_2";
			};
		};
		
		class Exhausts {
			class Exhaust1 {
				position = "el start";
				direction = "el konec";
				effect = "ExhaustsEffect";
			};
			
			class Exhaust2 {
				position = "er start";
				direction = "er konec";
				effect = "ExhaustsEffect";
			};
		};
		
		// internal camera viewing limitations
		class ViewPilot : ViewPilot {
			initAngleX = -30;
			minAngleX = -30;
			maxAngleX = 30;
			initAngleY = 0;
			minAngleY = -90;
			maxAngleY = 90;
			initFov = 0.95;
			minFov = 0.5;
			maxFov = 1.2;
		};
		
		class AnimationSources {
			class ReloadAnim {
				source = "reload";
				weapon = "M2";
			};
			
			class ReloadMagazine {
				source = "reloadmagazine";
				weapon = "M2";
			};
			
			class Revolving {
				source = "revolving";
				weapon = "M2";
			};
		};
		
		class UserActions {
			class Flip {
				displayName = "Flip DVP";
				position = "drivewheel";
				radius = "2";
				onlyForPlayer = "True";
				condition = "player in this";
				statement = "this setvectorup [0,0,1]";
			};
		};
		
		class Library {
			libTextDesc = "The Desert Patrol Vehicle (DPV), formerly called the Fast Attack Vehicle (FAV), is a high-speed, lightly-armored sandrail-like vehicle first used in combat during the Gulf War in 1991. Due to their dash speed and off-road mobility, the DPVs were used extensively during Operation Desert Storm. The first U.S. forces to enter Kuwait City were United States Navy SEALs in DPVs. The DPV is currently operated only by SEAL Team THREE, the unit assigned to the Middle East.";
		};
		castDriverShadow = true;
		driverAction = "dpv_Driver";
		cargoAction[] = {"dpv_codriver", "dpv_gunner"};
		unitInfoType = "UnitInfoShip";
		
		// threat (VSoft, VArmor, VAir), how threatening vehicle is to unit types
		threat[] = {1, 0.1, 0.4};

		
		class NVGMarkers {
			class NVGMarker01 {
				name = "nvg_marker";
				color[] = {0.03, 0.003, 0.003, 1};
				ambient[] = {0.003, 0.0003, 0.0003, 1};
				brightness = 0.001;
				blinking = true;
			};
		};
		
		class Reflectors {
			class Left {
				color[] = {0.8, 0.8, 1.0, 1.0};
				ambient[] = {0.07, 0.07, 0.07, 1.0};
				position = "L svetlo";
				direction = "konec L svetla";
				hitpoint = "L svetlo";
				selection = "L svetlo";
				size = 1;
				brightness = 1.0;
			};
			
			class Right {
				color[] = {0.8, 0.8, 1.0, 1.0};
				ambient[] = {0.07, 0.07, 0.07, 1.0};
				position = "P svetlo";
				direction = "konec P svetla";
				hitpoint = "P svetlo";
				selection = "P svetlo";
				size = 1;
				brightness = 1.0;
			};
		};
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"\dpv\data\dpv.paa"};
		
		class Damage {
			tex[] = {};
			mat[] = {};
		};
		outsideSoundFilter = 1;
		insideSoundCoef = 0.8;
		soundGear[] = {"", db-85, 1};
		soundGetIn[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_door", db-5, 1};
		soundGetOut[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_door", db-5, 1, 20};
		soundEngineOnInt[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_start", 0.177828, 1.0};
		soundEngineOnExt[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_start", 0.177828, 1.0, 100};
		soundEngineOffInt[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_stop", 0.177828, 1.0};
		soundEngineOffExt[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_stop", 0.177828, 1.0, 100};
		buildCrash0[] = {"Ca\sounds\Vehicles\Crash\crash_building_01", 0.707946, 1, 200};
		buildCrash1[] = {"Ca\sounds\Vehicles\Crash\crash_building_02", 0.707946, 1, 200};
		buildCrash2[] = {"Ca\sounds\Vehicles\Crash\crash_building_03", 0.707946, 1, 200};
		buildCrash3[] = {"Ca\sounds\Vehicles\Crash\crash_building_04", 0.707946, 1, 200};
		soundBuildingCrash[] = {"buildCrash0", 0.25, "buildCrash1", 0.25, "buildCrash2", 0.25, "buildCrash3", 0.25};
		WoodCrash0[] = {"Ca\sounds\Vehicles\Crash\crash_mix_wood_01", 0.707946, 1, 200};
		WoodCrash1[] = {"Ca\sounds\Vehicles\Crash\crash_mix_wood_02", 0.707946, 1, 200};
		WoodCrash2[] = {"Ca\sounds\Vehicles\Crash\crash_mix_wood_03", 0.707946, 1, 200};
		WoodCrash3[] = {"Ca\sounds\Vehicles\Crash\crash_mix_wood_04", 0.707946, 1, 200};
		WoodCrash4[] = {"Ca\sounds\Vehicles\Crash\crash_mix_wood_05", 0.707946, 1, 200};
		WoodCrash5[] = {"Ca\sounds\Vehicles\Crash\crash_mix_wood_06", 0.707946, 1, 200};
		soundWoodCrash[] = {"woodCrash0", 0.166, "woodCrash1", 0.166, "woodCrash2", 0.166, "woodCrash3", 0.166, "woodCrash4", 0.166, "woodCrash5", 0.166};
		ArmorCrash0[] = {"Ca\sounds\Vehicles\Crash\crash_vehicle_01", 0.707946, 1, 200};
		ArmorCrash1[] = {"Ca\sounds\Vehicles\Crash\crash_vehicle_02", 0.707946, 1, 200};
		ArmorCrash2[] = {"Ca\sounds\Vehicles\Crash\crash_vehicle_03", 0.707946, 1, 200};
		ArmorCrash3[] = {"Ca\sounds\Vehicles\Crash\crash_vehicle_04", 0.707946, 1, 200};
		soundArmorCrash[] = {"ArmorCrash0", 0.25, "ArmorCrash1", 0.25, "ArmorCrash2", 0.25, "ArmorCrash3", 0.25};
		
		class SoundEvents {
			class AccelerationIn {
				sound[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_accelerate_3", db-5, 1.0};
				limit = 0.4;
				expression = "(engineOn*(1-camPos))*gmeterZ";
			};
			
			class AccelerationOut {
				sound[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_accelerate_3", db-5, 1.0, 200};
				limit = 0.4;
				expression = "(engineOn*camPos)*gmeterZ";
			};
		};
		
		class Sounds {
			class Engine {
				sound[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_low", 0.177828, 1.4, 100};
				frequency = "(randomizer*0.05+0.95)*rpm";
				volume = "camPos*engineOn*((rpm factor[0.3, 0.4]) min (rpm factor[0.7, 0.5]))";
			};
			
			class EngineHighOut {
				sound[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_high", db0, 0.8, 300};
				frequency = "(randomizer*0.05+0.95)*rpm";
				volume = "camPos*engineOn*(rpm factor[0.5, 0.8])";
			};
			
			class IdleOut {
				sound[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_idle", db-5, 1.0, 100};
				frequency = "1";
				volume = "engineOn*camPos*(rpm factor[0.4, 0])";
			};
			
			class TiresRockOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-rock2", 0.316228, 1.0, 30};
				frequency = "1";
				volume = "camPos*rock*(speed factor[2, 20])";
			};
			
			class TiresSandOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-sand2", 0.316228, 1.0, 30};
				frequency = "1";
				volume = "camPos*sand*(speed factor[2, 20])";
			};
			
			class TiresGrassOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-grass2", 0.316228, 1.0, 30};
				frequency = "1";
				volume = "camPos*grass*(speed factor[2, 20])";
			};
			
			class TiresMudOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-mud2", 0.316228, 1.0, 30};
				frequency = "1";
				volume = "camPos*mud*(speed factor[2, 20])";
			};
			
			class TiresGravelOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-gravel2", 0.316228, 1.0, 30};
				frequency = "1";
				volume = "camPos*gravel*(speed factor[2, 20])";
			};
			
			class TiresAsphaltOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\ext\ext-tires-asphalt3", 0.316228, 1.0, 30};
				frequency = "1";
				volume = "camPos*asphalt*(speed factor[2, 20])";
			};
			
			class NoiseOut {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Noises\ext\noise2", 0.1, 1.0, 30};
				frequency = "1";
				volume = "camPos*(damper0 max 0.03)*(speed factor[0, 8])";
			};
			
			class EngineLowIn {
				sound[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_low", 0.316228, 1.4};
				frequency = "(randomizer*0.05+0.95)*rpm";
				volume = "(1-camPos)*engineOn*((rpm factor[0.3, 0.4]) min (rpm factor[0.7, 0.45]))";
			};
			
			class EngineHighIn {
				sound[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_high", db0, 0.8};
				frequency = "(randomizer*0.05+0.95)*rpm";
				volume = "(1-camPos)*engineOn*(rpm factor[0.5, 0.8])";
			};
			
			class IdleIn {
				sound[] = {"ca\Sounds_E\Wheeled_E\SUV\SUV_ext_idle", 0.316228, 1.0};
				frequency = "1";
				volume = "engineOn*(rpm factor[0.4, 0])*(1-camPos)";
			};
			
			class TiresRockIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-rock2", 0.316228, 1.0};
				frequency = "1";
				volume = "(1-camPos)*rock*(speed factor[2, 20])";
			};
			
			class TiresSandIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-sand2", 0.316228, 1.0};
				frequency = "1";
				volume = "(1-camPos)*sand*(speed factor[2, 20])";
			};
			
			class TiresGrassIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-grass2", 0.316228, 1.0};
				frequency = "1";
				volume = "(1-camPos)*grass*(speed factor[2, 20])";
			};
			
			class TiresMudIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-mud2", 0.316228, 1.0};
				frequency = "1";
				volume = "(1-camPos)*mud*(speed factor[2, 20])";
			};
			
			class TiresGravelIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-gravel2", 0.316228, 1.0};
				frequency = "1";
				volume = "(1-camPos)*gravel*(speed factor[2, 20])";
			};
			
			class TiresAsphaltIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Tires\int\int-tires-asphalt3", 0.316228, 1.0};
				frequency = "1";
				volume = "(1-camPos)*asphalt*(speed factor[2, 20])";
			};
			
			class NoiseIn {
				sound[] = {"\ca\SOUNDS\Vehicles\Wheeled\Noises\int\noise2", 0.177828, 1.0};
				frequency = "1";
				volume = "(damper0 max 0.03)*(speed factor[0, 8])*(1-camPos)";
			};
			
			class Movement {
				sound = "soundEnviron";
				frequency = "1";
				volume = "0";
			};
		};
	};
	
	class dpv_woodland : dpv {
		displayName = "Chenowth DPV Woodland";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"\dpv\data\dpv_woodland.paa"};
	};
	
	class dpv_black : dpv {
		displayName = "Chenowth DPV black";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"\dpv\data\dpv_black.paa"};
	};
	
		class Buggy_DZ : dpv {
		displayName = "Oring Buggy";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"\dpv\data\dpv_black.paa"};
	};
	
	class dpv_woodlandcamo : dpv {
		displayName = "Chenowth DPV woodland Camo";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"\dpv\data\dpv_woodlandcamo.paa"};
	};
	
	class dpv_desertcamo : dpv {
		displayName = "Chenowth DPV Desert Camo";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"\dpv\data\dpv_desertcamo.paa"};
	};
};
